# Generated by Django 6.0.2 on 2026-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=20)),
                ('e_name', models.CharField(max_length=100)),
                ('e_desgination', models.CharField(max_length=20)),
                ('e_team', models.CharField(max_length=20)),
                ('e_salary', models.IntegerField(max_length=10)),
                ('e_doj', models.DateField()),
            ],
        ),
    ]
